<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    public function run()
    {
        $products = [
            // Electronics (category_id: 1)
            [
                'name' => 'Smartphone X Pro',
                'slug' => 'smartphone-x-pro',
                'short_description' => 'Flagship smartphone with AMOLED display',
                'description' => '6.7" Super AMOLED, 256GB storage, 108MP triple camera, 5000mAh battery',
                'price' => 899.99,
                'compare_price' => 999.99,
                'category_id' => 1,
                'image' => 'products/electronics/smartphone.jpg',
                'gallery' => ['products/electronics/smartphone-1.jpg', 'products/electronics/smartphone-2.jpg'],
                'is_featured' => true,
                'quantity' => 75,
                'rating' => 4.7,
            ],
            [
                'name' => 'Noise Cancelling Headphones',
                'slug' => 'noise-cancelling-headphones',
                'short_description' => 'Industry-leading active noise cancellation',
                'description' => 'Bluetooth 5.2, 40hrs battery, touch controls, built-in mic',
                'price' => 349.99,
                'compare_price' => 399.99,
                'category_id' => 1,
                'image' => 'products/electronics/headphones.jpg',
                'gallery' => ['products/electronics/headphones-1.jpg', 'products/electronics/headphones-2.jpg'],
                'is_featured' => true,
                'quantity' => 40,
                'rating' => 4.8,
            ],
            [
                'name' => '4K Ultra HD Smart TV',
                'slug' => '4k-ultra-hd-smart-tv',
                'short_description' => '65-inch 4K UHD LED Smart TV',
                'description' => 'HDR10+, Dolby Vision, Smart OS with voice control, 3 HDMI ports',
                'price' => 799.99,
                'compare_price' => 1099.99,
                'category_id' => 1,
                'image' => 'products/electronics/tv.jpg',
                'gallery' => ['products/electronics/tv-1.jpg', 'products/electronics/tv-2.jpg'],
                'is_featured' => true,
                'quantity' => 25,
                'rating' => 4.6,
            ],
            [
                'name' => 'Gaming Laptop',
                'slug' => 'gaming-laptop',
                'short_description' => 'High-performance gaming laptop',
                'description' => 'RTX 3070, 16GB RAM, 1TB SSD, 144Hz display, RGB keyboard',
                'price' => 1499.99,
                'compare_price' => 1799.99,
                'category_id' => 1,
                'image' => 'products/electronics/laptop.jpg',
                'gallery' => ['products/electronics/laptop-1.jpg', 'products/electronics/laptop-2.jpg'],
                'is_featured' => true,
                'quantity' => 15,
                'rating' => 4.9,
            ],
            [
                'name' => 'Smart Watch Pro',
                'slug' => 'smart-watch-pro',
                'short_description' => 'Advanced health and fitness tracker',
                'description' => 'Blood oxygen monitor, ECG, GPS, 7-day battery, swim-proof',
                'price' => 249.99,
                'compare_price' => 299.99,
                'category_id' => 1,
                'image' => 'products/electronics/smartwatch.jpg',
                'gallery' => ['products/electronics/smartwatch-1.jpg', 'products/electronics/smartwatch-2.jpg'],
                'is_featured' => false,
                'quantity' => 60,
                'rating' => 4.5,
            ],

            // Fashion (category_id: 2)
            [
                'name' => 'Men\'s Casual Shirt',
                'slug' => 'mens-casual-shirt',
                'short_description' => 'Comfortable cotton casual shirt',
                'description' => '100% cotton, regular fit, machine wash, available in multiple colors',
                'price' => 29.99,
                'compare_price' => 39.99,
                'category_id' => 2,
                'image' => 'products/fashion/shirt.jpg',
                'gallery' => ['products/fashion/shirt-1.jpg', 'products/fashion/shirt-2.jpg'],
                'is_featured' => false,
                'quantity' => 120,
                'rating' => 4.3,
            ],
            [
                'name' => 'Women\'s Summer Dress',
                'slug' => 'womens-summer-dress',
                'short_description' => 'Lightweight floral summer dress',
                'description' => 'Breathable fabric, A-line cut, midi length, perfect for warm weather',
                'price' => 45.99,
                'compare_price' => 59.99,
                'category_id' => 2,
                'image' => 'products/fashion/dress.jpg',
                'gallery' => ['products/fashion/dress-1.jpg', 'products/fashion/dress-2.jpg'],
                'is_featured' => true,
                'quantity' => 85,
                'rating' => 4.6,
            ],
            [
                'name' => 'Leather Wallet',
                'slug' => 'leather-wallet',
                'short_description' => 'Genuine leather bifold wallet',
                'description' => 'Multiple card slots, ID window, RFID protection, premium stitching',
                'price' => 49.99,
                'compare_price' => 69.99,
                'category_id' => 2,
                'image' => 'products/fashion/wallet.jpg',
                'gallery' => ['products/fashion/wallet-1.jpg', 'products/fashion/wallet-2.jpg'],
                'is_featured' => false,
                'quantity' => 90,
                'rating' => 4.4,
            ],
            [
                'name' => 'Running Shoes',
                'slug' => 'running-shoes',
                'short_description' => 'Lightweight running shoes',
                'description' => 'Breathable mesh, cushioned sole, shock absorption, available in multiple colors',
                'price' => 79.99,
                'compare_price' => 99.99,
                'category_id' => 2,
                'image' => 'products/fashion/shoes.jpg',
                'gallery' => ['products/fashion/shoes-1.jpg', 'products/fashion/shoes-2.jpg'],
                'is_featured' => true,
                'quantity' => 65,
                'rating' => 4.7,
            ],
            [
                'name' => 'Designer Sunglasses',
                'slug' => 'designer-sunglasses',
                'short_description' => 'UV protection polarized sunglasses',
                'description' => '100% UV protection, polarized lenses, lightweight frame, stylish design',
                'price' => 89.99,
                'compare_price' => 129.99,
                'category_id' => 2,
                'image' => 'products/fashion/sunglasses.jpg',
                'gallery' => ['products/fashion/sunglasses-1.jpg', 'products/fashion/sunglasses-2.jpg'],
                'is_featured' => false,
                'quantity' => 45,
                'rating' => 4.5,
            ],

            // Home & Kitchen (category_id: 3)
            [
                'name' => 'Air Fryer',
                'slug' => 'air-fryer',
                'short_description' => 'Digital air fryer with multiple functions',
                'description' => '5.8L capacity, 8 presets, digital display, non-stick basket, 1700W',
                'price' => 99.99,
                'compare_price' => 129.99,
                'category_id' => 3,
                'image' => 'products/home/airfryer.jpg',
                'gallery' => ['products/home/airfryer-1.jpg', 'products/home/airfryer-2.jpg'],
                'is_featured' => true,
                'quantity' => 35,
                'rating' => 4.8,
            ],
            [
                'name' => 'Non-Stick Cookware Set',
                'slug' => 'non-stick-cookware-set',
                'short_description' => '10-piece non-stick cookware set',
                'description' => 'Includes pots, pans, utensils, glass lids, oven safe up to 350°F',
                'price' => 149.99,
                'compare_price' => 199.99,
                'category_id' => 3,
                'image' => 'products/home/cookware.jpg',
                'gallery' => ['products/home/cookware-1.jpg', 'products/home/cookware-2.jpg'],
                'is_featured' => true,
                'quantity' => 20,
                'rating' => 4.6,
            ],
            [
                'name' => 'Robot Vacuum Cleaner',
                'slug' => 'robot-vacuum-cleaner',
                'short_description' => 'Smart robot vacuum with app control',
                'description' => 'Laser navigation, 150min runtime, auto recharge, works with Alexa',
                'price' => 299.99,
                'compare_price' => 399.99,
                'category_id' => 3,
                'image' => 'products/home/vacuum.jpg',
                'gallery' => ['products/home/vacuum-1.jpg', 'products/home/vacuum-2.jpg'],
                'is_featured' => false,
                'quantity' => 18,
                'rating' => 4.7,
            ],
            [
                'name' => 'Memory Foam Mattress',
                'slug' => 'memory-foam-mattress',
                'short_description' => '10-inch gel memory foam mattress',
                'description' => 'Medium-firm, pressure relief, cooling gel, hypoallergenic, 10-year warranty',
                'price' => 499.99,
                'compare_price' => 699.99,
                'category_id' => 3,
                'image' => 'products/home/mattress.jpg',
                'gallery' => ['products/home/mattress-1.jpg', 'products/home/mattress-2.jpg'],
                'is_featured' => true,
                'quantity' => 12,
                'rating' => 4.9,
            ],
            [
                'name' => 'Smart LED Bulbs',
                'slug' => 'smart-led-bulbs',
                'short_description' => 'WiFi enabled color changing bulbs',
                'description' => '16 million colors, voice control, scheduling, works with Alexa/Google Home',
                'price' => 39.99,
                'compare_price' => 59.99,
                'category_id' => 3,
                'image' => 'products/home/ledbulb.jpg',
                'gallery' => ['products/home/ledbulb-1.jpg', 'products/home/ledbulb-2.jpg'],
                'is_featured' => false,
                'quantity' => 80,
                'rating' => 4.4,
            ],

            // Beauty (category_id: 4)
            [
                'name' => 'Anti-Aging Cream',
                'slug' => 'anti-aging-cream',
                'short_description' => 'Premium night repair cream',
                'description' => 'Reduces wrinkles, hydrates skin, contains hyaluronic acid and retinol',
                'price' => 59.99,
                'compare_price' => 79.99,
                'category_id' => 4,
                'image' => 'products/beauty/cream.jpg',
                'gallery' => ['products/beauty/cream-1.jpg', 'products/beauty/cream-2.jpg'],
                'is_featured' => true,
                'quantity' => 55,
                'rating' => 4.5,
            ],
            [
                'name' => 'Electric Toothbrush',
                'slug' => 'electric-toothbrush',
                'short_description' => 'Sonic toothbrush with 3 modes',
                'description' => '30000 vibrations/min, 2-week battery, pressure sensor, includes 2 brush heads',
                'price' => 49.99,
                'compare_price' => 69.99,
                'category_id' => 4,
                'image' => 'products/beauty/toothbrush.jpg',
                'gallery' => ['products/beauty/toothbrush-1.jpg', 'products/beauty/toothbrush-2.jpg'],
                'is_featured' => false,
                'quantity' => 70,
                'rating' => 4.7,
            ],
            [
                'name' => 'Hair Dryer',
                'slug' => 'hair-dryer',
                'short_description' => 'Professional ionic hair dryer',
                'description' => '1875W, 3 heat/speed settings, concentrator nozzle, reduces frizz',
                'price' => 89.99,
                'compare_price' => 119.99,
                'category_id' => 4,
                'image' => 'products/beauty/hairdryer.jpg',
                'gallery' => ['products/beauty/hairdryer-1.jpg', 'products/beauty/hairdryer-2.jpg'],
                'is_featured' => false,
                'quantity' => 30,
                'rating' => 4.6,
            ],
            [
                'name' => 'Makeup Brush Set',
                'slug' => 'makeup-brush-set',
                'short_description' => '12-piece professional brush set',
                'description' => 'Synthetic bristles, ergonomic handles, includes travel case',
                'price' => 39.99,
                'compare_price' => 59.99,
                'category_id' => 4,
                'image' => 'products/beauty/brushes.jpg',
                'gallery' => ['products/beauty/brushes-1.jpg', 'products/beauty/brushes-2.jpg'],
                'is_featured' => false,
                'quantity' => 90,
                'rating' => 4.4,
            ],
            [
                'name' => 'Perfume Gift Set',
                'slug' => 'perfume-gift-set',
                'short_description' => 'Luxury fragrance collection',
                'description' => 'Includes 3 x 20ml Eau de Parfum in elegant gift box',
                'price' => 79.99,
                'compare_price' => 99.99,
                'category_id' => 4,
                'image' => 'products/beauty/perfume.jpg',
                'gallery' => ['products/beauty/perfume-1.jpg', 'products/beauty/perfume-2.jpg'],
                'is_featured' => true,
                'quantity' => 25,
                'rating' => 4.8,
            ],

            // Sports (category_id: 5)
            [
                'name' => 'Yoga Mat',
                'slug' => 'yoga-mat',
                'short_description' => 'Eco-friendly non-slip yoga mat',
                'description' => '6mm thick, moisture-resistant, includes carrying strap',
                'price' => 29.99,
                'compare_price' => 39.99,
                'category_id' => 5,
                'image' => 'products/sports/yogamat.jpg',
                'gallery' => ['products/sports/yogamat-1.jpg', 'products/sports/yogamat-2.jpg'],
                'is_featured' => false,
                'quantity' => 60,
                'rating' => 4.5,
            ],
            [
                'name' => 'Dumbbell Set',
                'slug' => 'dumbbell-set',
                'short_description' => 'Adjustable weight dumbbells',
                'description' => '5-25lbs adjustable in 5lb increments, non-slip grip',
                'price' => 129.99,
                'compare_price' => 159.99,
                'category_id' => 5,
                'image' => 'products/sports/dumbbells.jpg',
                'gallery' => ['products/sports/dumbbells-1.jpg', 'products/sports/dumbbells-2.jpg'],
                'is_featured' => true,
                'quantity' => 20,
                'rating' => 4.7,
            ],
            [
                'name' => 'Running Watch',
                'slug' => 'running-watch',
                'short_description' => 'GPS running watch with heart rate',
                'description' => 'Built-in GPS, optical HR, 7-day battery, water resistant to 50m',
                'price' => 199.99,
                'compare_price' => 249.99,
                'category_id' => 5,
                'image' => 'products/sports/watch.jpg',
                'gallery' => ['products/sports/watch-1.jpg', 'products/sports/watch-2.jpg'],
                'is_featured' => true,
                'quantity' => 35,
                'rating' => 4.8,
            ],
            [
                'name' => 'Camping Tent',
                'slug' => 'camping-tent',
                'short_description' => '4-person waterproof tent',
                'description' => 'Easy setup, rainfly included, ventilation windows, carry bag',
                'price' => 149.99,
                'compare_price' => 199.99,
                'category_id' => 5,
                'image' => 'products/sports/tent.jpg',
                'gallery' => ['products/sports/tent-1.jpg', 'products/sports/tent-2.jpg'],
                'is_featured' => false,
                'quantity' => 15,
                'rating' => 4.6,
            ],
            [
                'name' => 'Bicycle',
                'slug' => 'mountain-bicycle',
                'short_description' => '21-speed mountain bike',
                'description' => 'Aluminum frame, front suspension, disc brakes, includes tools',
                'price' => 399.99,
                'compare_price' => 499.99,
                'category_id' => 5,
                'image' => 'products/sports/bike.jpg',
                'gallery' => ['products/sports/bike-1.jpg', 'products/sports/bike-2.jpg'],
                'is_featured' => true,
                'quantity' => 10,
                'rating' => 4.9,
            ],

            // Additional products to reach 50
            // Electronics
            [
                'name' => 'Bluetooth Speaker',
                'slug' => 'bluetooth-speaker',
                'short_description' => 'Portable waterproof speaker',
                'description' => '20hr playtime, IPX7 waterproof, built-in mic for calls',
                'price' => 79.99,
                'compare_price' => 99.99,
                'category_id' => 1,
                'image' => 'products/electronics/speaker.jpg',
                'gallery' => ['products/electronics/speaker-1.jpg', 'products/electronics/speaker-2.jpg'],
                'is_featured' => false,
                'quantity' => 50,
                'rating' => 4.5,
            ],
            [
                'name' => 'External SSD',
                'slug' => 'external-ssd',
                'short_description' => '1TB portable SSD drive',
                'description' => 'USB-C, 1050MB/s read speed, shock resistant, compact design',
                'price' => 129.99,
                'compare_price' => 159.99,
                'category_id' => 1,
                'image' => 'products/electronics/ssd.jpg',
                'gallery' => ['products/electronics/ssd-1.jpg', 'products/electronics/ssd-2.jpg'],
                'is_featured' => false,
                'quantity' => 40,
                'rating' => 4.8,
            ],
            [
                'name' => 'Wireless Earbuds',
                'slug' => 'wireless-earbuds',
                'short_description' => 'True wireless stereo earbuds',
                'description' => 'Bluetooth 5.0, 24hr battery with case, touch controls, IPX5 sweatproof',
                'price' => 59.99,
                'compare_price' => 79.99,
                'category_id' => 1,
                'image' => 'products/electronics/earbuds.jpg',
                'gallery' => ['products/electronics/earbuds-1.jpg', 'products/electronics/earbuds-2.jpg'],
                'is_featured' => false,
                'quantity' => 65,
                'rating' => 4.4,
            ],
            [
                'name' => 'Tablet',
                'slug' => '10-inch-tablet',
                'short_description' => '10.1" HD tablet with stylus',
                'description' => '128GB storage, 4GB RAM, dual cameras, includes stylus pen',
                'price' => 199.99,
                'compare_price' => 249.99,
                'category_id' => 1,
                'image' => 'products/electronics/tablet.jpg',
                'gallery' => ['products/electronics/tablet-1.jpg', 'products/electronics/tablet-2.jpg'],
                'is_featured' => false,
                'quantity' => 30,
                'rating' => 4.3,
            ],
            [
                'name' => 'Drone with Camera',
                'slug' => 'drone-with-camera',
                'short_description' => '4K camera drone with GPS',
                'description' => '30min flight time, 1km range, follow me mode, includes carrying case',
                'price' => 299.99,
                'compare_price' => 399.99,
                'category_id' => 1,
                'image' => 'products/electronics/drone.jpg',
                'gallery' => ['products/electronics/drone-1.jpg', 'products/electronics/drone-2.jpg'],
                'is_featured' => true,
                'quantity' => 15,
                'rating' => 4.7,
            ],

            // Fashion
            [
                'name' => 'Leather Jacket',
                'slug' => 'leather-jacket',
                'short_description' => 'Genuine leather biker jacket',
                'description' => '100% lambskin leather, quilted lining, multiple pockets',
                'price' => 199.99,
                'compare_price' => 299.99,
                'category_id' => 2,
                'image' => 'products/fashion/jacket.jpg',
                'gallery' => ['products/fashion/jacket-1.jpg', 'products/fashion/jacket-2.jpg'],
                'is_featured' => true,
                'quantity' => 25,
                'rating' => 4.8,
            ],
            [
                'name' => 'Silk Scarf',
                'slug' => 'silk-scarf',
                'short_description' => 'Luxury printed silk scarf',
                'description' => '100% mulberry silk, hand-rolled edges, 90x90cm',
                'price' => 49.99,
                'compare_price' => 69.99,
                'category_id' => 2,
                'image' => 'products/fashion/scarf.jpg',
                'gallery' => ['products/fashion/scarf-1.jpg', 'products/fashion/scarf-2.jpg'],
                'is_featured' => false,
                'quantity' => 40,
                'rating' => 4.6,
            ],
            [
                'name' => 'Denim Jeans',
                'slug' => 'denim-jeans',
                'short_description' => 'Slim fit stretch denim jeans',
                'description' => '98% cotton, 2% elastane, mid-rise, five-pocket style',
                'price' => 59.99,
                'compare_price' => 79.99,
                'category_id' => 2,
                'image' => 'products/fashion/jeans.jpg',
                'gallery' => ['products/fashion/jeans-1.jpg', 'products/fashion/jeans-2.jpg'],
                'is_featured' => false,
                'quantity' => 55,
                'rating' => 4.5,
            ],
            [
                'name' => 'Winter Coat',
                'slug' => 'winter-coat',
                'short_description' => 'Waterproof insulated winter coat',
                'description' => 'Thermal insulation, waterproof outer, detachable hood, multiple pockets',
                'price' => 149.99,
                'compare_price' => 199.99,
                'category_id' => 2,
                'image' => 'products/fashion/coat.jpg',
                'gallery' => ['products/fashion/coat-1.jpg', 'products/fashion/coat-2.jpg'],
                'is_featured' => true,
                'quantity' => 30,
                'rating' => 4.7,
            ],
            [
                'name' => 'Formal Shoes',
                'slug' => 'formal-shoes',
                'short_description' => 'Oxford leather formal shoes',
                'description' => 'Genuine leather, cushioned insole, durable rubber sole',
                'price' => 89.99,
                'compare_price' => 119.99,
                'category_id' => 2,
                'image' => 'products/fashion/formalshoes.jpg',
                'gallery' => ['products/fashion/formalshoes-1.jpg', 'products/fashion/formalshoes-2.jpg'],
                'is_featured' => false,
                'quantity' => 35,
                'rating' => 4.6,
            ],

            // Home & Kitchen
            [
                'name' => 'Coffee Maker',
                'slug' => 'coffee-maker',
                'short_description' => 'Programmable 12-cup coffee maker',
                'description' => 'Auto shutoff, pause & serve, permanent filter, glass carafe',
                'price' => 49.99,
                'compare_price' => 69.99,
                'category_id' => 3,
                'image' => 'products/home/coffeemaker.jpg',
                'gallery' => ['products/home/coffeemaker-1.jpg', 'products/home/coffeemaker-2.jpg'],
                'is_featured' => false,
                'quantity' => 45,
                'rating' => 4.5,
            ],
            [
                'name' => 'Cutlery Set',
                'slug' => 'cutlery-set',
                'short_description' => '18-piece stainless steel cutlery set',
                'description' => 'Mirror polish, dishwasher safe, includes serving pieces',
                'price' => 39.99,
                'compare_price' => 59.99,
                'category_id' => 3,
                'image' => 'products/home/cutlery.jpg',
                'gallery' => ['products/home/cutlery-1.jpg', 'products/home/cutlery-2.jpg'],
                'is_featured' => false,
                'quantity' => 60,
                'rating' => 4.4,
            ],
            [
                'name' => 'Air Purifier',
                'slug' => 'air-purifier',
                'short_description' => 'HEPA air purifier for large rooms',
                'description' => 'True HEPA filter, 3 fan speeds, smart sensor, covers 500 sq ft',
                'price' => 179.99,
                'compare_price' => 229.99,
                'category_id' => 3,
                'image' => 'products/home/airpurifier.jpg',
                'gallery' => ['products/home/airpurifier-1.jpg', 'products/home/airpurifier-2.jpg'],
                'is_featured' => true,
                'quantity' => 20,
                'rating' => 4.7,
            ],
            [
                'name' => 'Bedding Set',
                'slug' => 'bedding-set',
                'short_description' => 'Queen size 6-piece bedding set',
                'description' => '100% Egyptian cotton, 600 thread count, includes 4 pillowcases',
                'price' => 89.99,
                'compare_price' => 119.99,
                'category_id' => 3,
                'image' => 'products/home/bedding.jpg',
                'gallery' => ['products/home/bedding-1.jpg', 'products/home/bedding-2.jpg'],
                'is_featured' => false,
                'quantity' => 35,
                'rating' => 4.6,
            ],
            [
                'name' => 'Food Processor',
                'slug' => 'food-processor',
                'short_description' => '10-cup capacity food processor',
                'description' => '700W motor, 4 included blades, dishwasher safe parts',
                'price' => 79.99,
                'compare_price' => 99.99,
                'category_id' => 3,
                'image' => 'products/home/foodprocessor.jpg',
                'gallery' => ['products/home/foodprocessor-1.jpg', 'products/home/foodprocessor-2.jpg'],
                'is_featured' => false,
                'quantity' => 25,
                'rating' => 4.5,
            ],

            // Beauty
            [
                'name' => 'Vitamin C Serum',
                'slug' => 'vitamin-c-serum',
                'short_description' => 'Brightening vitamin C serum',
                'description' => '20% vitamin C, hyaluronic acid, reduces dark spots, vegan formula',
                'price' => 29.99,
                'compare_price' => 39.99,
                'category_id' => 4,
                'image' => 'products/beauty/serum.jpg',
                'gallery' => ['products/beauty/serum-1.jpg', 'products/beauty/serum-2.jpg'],
                'is_featured' => false,
                'quantity' => 75,
                'rating' => 4.6,
            ],
            [
                'name' => 'LED Face Mask',
                'slug' => 'led-face-mask',
                'short_description' => 'Professional LED light therapy mask',
                'description' => '7 colors, 3 intensity levels, rechargeable, FDA cleared',
                'price' => 149.99,
                'compare_price' => 199.99,
                'category_id' => 4,
                'image' => 'products/beauty/ledmask.jpg',
                'gallery' => ['products/beauty/ledmask-1.jpg', 'products/beauty/ledmask-2.jpg'],
                'is_featured' => true,
                'quantity' => 15,
                'rating' => 4.7,
            ],
            [
                'name' => 'Hair Straightener',
                'slug' => 'hair-straightener',
                'short_description' => 'Professional ceramic flat iron',
                'description' => '1-inch plates, adjustable temp up to 450°F, auto shutoff',
                'price' => 59.99,
                'compare_price' => 79.99,
                'category_id' => 4,
                'image' => 'products/beauty/straightener.jpg',
                'gallery' => ['products/beauty/straightener-1.jpg', 'products/beauty/straightener-2.jpg'],
                'is_featured' => false,
                'quantity' => 40,
                'rating' => 4.5,
            ],
            [
                'name' => 'Makeup Palette',
                'slug' => 'makeup-palette',
                'short_description' => '18-shade eyeshadow palette',
                'description' => 'Matte and shimmer finishes, highly pigmented, cruelty-free',
                'price' => 24.99,
                'compare_price' => 34.99,
                'category_id' => 4,
                'image' => 'products/beauty/palette.jpg',
                'gallery' => ['products/beauty/palette-1.jpg', 'products/beauty/palette-2.jpg'],
                'is_featured' => false,
                'quantity' => 85,
                'rating' => 4.4,
            ],
            [
                'name' => 'Electric Shaver',
                'slug' => 'electric-shaver',
                'short_description' => 'Wet/dry rotary shaver',
                'description' => '3 floating heads, 60min cordless use, waterproof, includes travel case',
                'price' => 69.99,
                'compare_price' => 89.99,
                'category_id' => 4,
                'image' => 'products/beauty/shaver.jpg',
                'gallery' => ['products/beauty/shaver-1.jpg', 'products/beauty/shaver-2.jpg'],
                'is_featured' => false,
                'quantity' => 50,
                'rating' => 4.6,
            ],

            // Sports
            [
                'name' => 'Fitness Tracker',
                'slug' => 'fitness-tracker',
                'short_description' => 'Waterproof activity tracker',
                'description' => 'Tracks steps, calories, sleep, heart rate, 7-day battery',
                'price' => 49.99,
                'compare_price' => 69.99,
                'category_id' => 5,
                'image' => 'products/sports/tracker.jpg',
                'gallery' => ['products/sports/tracker-1.jpg', 'products/sports/tracker-2.jpg'],
                'is_featured' => false,
                'quantity' => 65,
                'rating' => 4.5,
            ],
            [
                'name' => 'Resistance Bands',
                'slug' => 'resistance-bands',
                'short_description' => '5-piece workout bands set',
                'description' => 'Includes 5 resistance levels, door anchor, ankle straps, carry bag',
                'price' => 29.99,
                'compare_price' => 39.99,
                'category_id' => 5,
                'image' => 'products/sports/bands.jpg',
                'gallery' => ['products/sports/bands-1.jpg', 'products/sports/bands-2.jpg'],
                'is_featured' => false,
                'quantity' => 80,
                'rating' => 4.3,
            ],
            [
                'name' => 'Hiking Backpack',
                'slug' => 'hiking-backpack',
                'short_description' => '40L waterproof hiking backpack',
                'description' => 'Multiple compartments, hydration compatible, adjustable straps',
                'price' => 79.99,
                'compare_price' => 99.99,
                'category_id' => 5,
                'image' => 'products/sports/backpack.jpg',
                'gallery' => ['products/sports/backpack-1.jpg', 'products/sports/backpack-2.jpg'],
                'is_featured' => false,
                'quantity' => 25,
                'rating' => 4.7,
            ],
            [
                'name' => 'Yoga Block',
                'slug' => 'yoga-block',
                'short_description' => 'Eco-friendly cork yoga block',
                'description' => '4" x 6" x 9", lightweight, non-slip surface',
                'price' => 14.99,
                'compare_price' => 19.99,
                'category_id' => 5,
                'image' => 'products/sports/yogablock.jpg',
                'gallery' => ['products/sports/yogablock-1.jpg', 'products/sports/yogablock-2.jpg'],
                'is_featured' => false,
                'quantity' => 90,
                'rating' => 4.4,
            ],
            [
                'name' => 'Jump Rope',
                'slug' => 'jump-rope',
                'short_description' => 'Adjustable speed jump rope',
                'description' => 'Ball bearings for smooth rotation, foam handles, length adjustable',
                'price' => 12.99,
                'compare_price' => 16.99,
                'category_id' => 5,
                'image' => 'products/sports/jumprope.jpg',
                'gallery' => ['products/sports/jumprope-1.jpg', 'products/sports/jumprope-2.jpg'],
                'is_featured' => false,
                'quantity' => 110,
                'rating' => 4.2,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}